# .github/workflows/mlops.yml

name: MLOps Pipeline

permissions:
  contents: read
  id-token: write
  

on:
  push:
    branches: [ main ]

# 2. JOBS: The different stages of our assembly line
jobs:
  # Job 1: Test the code
  test:
    runs-on: ubuntu-latest # Use a standard Ubuntu runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Get the latest code from the repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List repository (debug)
      run: |
        ls -R .

    - name: Run tests with pytest
      env:
        PYTHONPATH: src
      run: |
        python -m pytest test/ -v

  # Job 2: Train the model
  train:
    # This job depends on the 'test' job. It will only run if 'test' completes successfully.
    needs: test
    runs-on: ubuntu-latest
    
    # Only run this job on pushes to the main branch, not on pull requests.
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies #2
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure AWS Credentials
      if: ${{ secrets.AWS_ACCESS_KEY_ID && secrets.AWS_SECRET_ACCESS_KEY }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Or your bucket's region

    - name: Install DVC (for data pull)
      if: ${{ secrets.AWS_ACCESS_KEY_ID && secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python -m pip install --upgrade pip
        pip install 'dvc[s3]'

    - name: Pull data from DVC remote storage
      if: ${{ secrets.AWS_ACCESS_KEY_ID && secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        dvc pull # Pulls the latest data from the S3 bucket

    - name: Process data
      run: |
        python src/feature_engineering/process_data.py

    - name: Train model
      run: |
        python src/modeling/train.py --model_type RandomForest --n_estimators 100

  # Job 3: Deploy the model
  deploy:
    # This job depends on the 'train' job.
    needs: train
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make deploy script executable
      run: chmod +x src/deployment/deploy.sh

    - name: Run deployment script
      run: |
        ./src/deployment/deploy.sh